node{
      docker.image('golang:1.7.3-alpine').inside {

         withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'AWS',
                            usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]){

            git 'https://github.com/voyages-sncf-technologies/hackathon-terraform.git'

            stage("build"){
                  sh 'pwd; cd helloworld; GOARCH=386 GOOS=linux GOPATH=$PWD go build helloworld.go;'
            }

            stage("package"){
                  sh 'pwd; cd helloworld;  tar czvf helloworld.tar.gz index.html img/hackathon.png img/chaton.png helloworld hackathon.service'
            }

            stage("archive"){
                archive includes: 'helloworld/*.tar.gz'
            }

            stage("report"){
              sh 'cd helloworld;ls -l'
            }
        }
    }
}

