node{
      docker.image('hashicorp/terraform:0.9.1').inside {

         withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'AWS',
                            usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]){

            git 'https://github.com/voyages-sncf-technologies/hackathon-terraform.git'

            stage("init"){
                  sh 'cd socle; terraform init -no-color'
            }

            stage("plan"){
                 sh 'cd socle; terraform plan -no-color'
            }

            stage("apply"){
                //timeout(time: 1, unit: 'HOURS') {
                //    input 'Apply?'
                    sh 'cd socle; terraform apply -no-color'
                //}
            }

            stage("report"){
              sh 'cd socle;terraform show -no-color'
            }
        }
    }
}

