node{
      docker.image('hashicorp/terraform:0.9.1').inside {

         withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'AWS',
                            usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY']]){

            git 'https://github.com/voyages-sncf-technologies/hackathon-terraform.git'

            stage("init"){
                  sh 'cd socle; terraform init'
            }

            stage("deploy"){
                wrap([$class: 'AnsiColorBuildWrapper']) {
                  sh 'cd socle; terraform plan'
                 }
                 shouldApply input 'Apply?'

                 if(shouldApply == true){
                    echo 'terraform apply'
                 }

            }

            stage("report"){
              sh 'cd socle;terraform show'
            }
        }
    }
}

